set -g status-style bg=default,fg=default
set -g window-status-current-style bg=default,fg=default,bold
set-option -g status-position top

bind-key c new-window -c "#{pane_current_path}"

bind-key '"' split-window -v -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"'"'
